Updated Raspberry Pi Client instructions
stream-pi/website pull request #17
Opened 2021-05-03 06:57 UTC by rnayabed

2021-05-03 07:16 UTC, rnayabed commented
Ref #13

2021-05-03 16:34 UTC, SamuelQuinones requested changes

2021-05-03 16:34 UTC, SamuelQuinones commented on install_instructions/client/raspberry-pi.md
> +editedBy: "rnayabed, SamuelQuinones"
editedBy should only ever be one user, this way we can track changes back to a specific user

2021-05-03 16:34 UTC, SamuelQuinones commented on install_instructions/client/raspberry-pi.md
> +**This method is NOT to be followed if your Raspberry Pi is running a 64 bit OS.**. Linux aarch64 builds are in the works, and will be available from the next release.
This was NEVER made clear to me and warrants a future discussion

2021-05-03 16:34 UTC, SamuelQuinones commented on install_instructions/client/raspberry-pi.md
> +## Instructions
"Client Instructions" was a conscious choice to eliminate confusion for end users, please undo this change

2021-05-03 16:34 UTC, SamuelQuinones commented on install_instructions/client/raspberry-pi.md
> +## Step 1
The three hash symbols was intentional for the Steps, please undo this change

2021-05-03 16:34 UTC, SamuelQuinones commented on install_instructions/client/raspberry-pi.md
> +## Step 2
The three hash symbols was intentional for the Steps, please undo this change

2021-05-03 16:34 UTC, SamuelQuinones commented on install_instructions/client/raspberry-pi.md
> +## Step 3
The three hash symbols was intentional for the Steps, please undo this change

2021-05-03 16:34 UTC, SamuelQuinones commented on install_instructions/client/raspberry-pi.md
> +/home/pi/StreamPiClient
If you change <YOURNAME> to pi here, it should be consistent everywhere

2021-05-03 16:34 UTC, SamuelQuinones commented on install_instructions/client/raspberry-pi.md
> +Be careful to not extract the zip in directories which cant be edited by non-root as it will cause Stream-Pi to not work correctly. For example: `/home/`.
I don't agree with this change: it seems to be more ambiguous, we should combine this change with what was already there

2021-05-03 16:34 UTC, SamuelQuinones commented on install_instructions/client/raspberry-pi.md
> -### Step 4
The three hash symbols was intentional for the Steps, please undo this change

2021-05-03 16:34 UTC, SamuelQuinones commented on install_instructions/client/raspberry-pi.md
> +## Step 5
The three hash symbols was intentional for the Steps, please undo this change

2021-05-03 16:34 UTC, SamuelQuinones commented on install_instructions/client/raspberry-pi.md
> +## Thats it!
We need to have this bit about the EULA

2021-05-25 12:18 UTC, rnayabed commented
Will not be used anymore since installers are now available.

2021-05-25 12:18 UTC, closed without merging